# # config file version
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: myk6db
    user: leakyadmin
    password: leakyadmin
    url: http://influxdb:8086
    isDefault: false
    editable: true
  - id: 1
    uid: 6AwMxn_7k
    orgId: 1
    name: prom1
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://prometheus:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData: { }
    readOnly: false
